### ISSUE TITLE
Applet doesnt Show in Fedora 40

### ISSUE THREAD

**Issue by philonmetal** [FrameworkComputer/tuned-gui#1]
Hello, this is my system:
Fedora 40 Gnome (fully updated as  of the day of writing this) 
Framework 13 (1240p)

I installed the script as shown in the readme and rebooted.
No Appindicator appears. tuneD script is installed and works
If i try to start the script manually i get these errors:
/home/phl/.local/bin/tuned_indicator.py: line 2: syntax error near unexpected token `'Gtk','
/home/phl/.local/bin/tuned_indicator.py: line 2: `gi.require_version('Gtk', '3.0')'

Did i something wrong?

**Comment by opetersen** [comment]
Hi,

I think you might be missing the gtk3 dependency -> `sudo dnf install gtk3`

**Comment by philonmetal** [comment]
Thanks for answering me, but the problem was the missing AppIndicator/KStatusNotifierItem which is mentioned in the Fedora script. I just didnt read it!
